### ISSUE TITLE
[BUG] Invalid kubernetes_version Format in Data Source vs. CLI Output (mismatch)

### ISSUE THREAD

**Issue by brokedba** [civo/terraform-provider-civo#363]
### Description

# Description:

I'm encountering an issue with the civo_kubernetes_version data source in the Civo Terraform Provider version 1.1.3. When attempting to create a Kubernetes cluster with the Talos distribution, the Terraform plan fails due to an invalid Kubernetes version format. The error message is as follows:

![Image](https://github.com/user-attachments/assets/74c52e90-7032-46cd-93dc-40e9a31cae34)

```lua
Error: invalid Kubernetes version format: '1.27.0' for cluster type 'talos'.

Please ensure your version matches the expected format, e.g., 'talos-vX.Y.Z'.

Available versions for 'talos':
- Stable: [talos-v1.5.0]
- Development: []
````

# Steps to Reproduce:

Define the civo_kubernetes_version data source with the following configuration:

```hcl
data "civo_kubernetes_version" "latest_talos" {
  filter {
    key    = "type"
    values = ["talos"]
  }
  filter {
    key    = "default"
    values = ["true"]
  }
  sort {
    key       = "label"
    direction = "desc"
  }
}
```
Output the versions retrieved by the data source:

```hcl
output "version_name" {
  value = data.civo_kubernetes_version.latest_talos.versions
}
```
- Run terraform plan.

- Observed Behavior:

The output from the data source is:

```json
[
  {
    "default": true,
    "label": "v1.27.0",
    "type": "talos",
    "version": "1.27.0"      <---- wrong
  }
]
```
- However, when using the Civo CLI, the expected format is returned:

```bash
civo kubernetes versions -o json | jq '.[] | select(.cluster_type == "talos" and .default == "true")'
```
```json

{
  "cluster_type": "talos",
  "default": "true",
  "label": "talos-v1.5.0",    <---- right
  "type": "stable",
  "version": "1.27.0"
}
```
# Expected Behavior:

The civo_kubernetes_version data source should return the label in the format 'talos-vX.Y.Z', consistent with the CLI output, to prevent version format errors during cluster creation.

Additional Information:

This discrepancy causes Terraform to fail with the following error:

```lua
Error: invalid Kubernetes version format: '1.27.0' for cluster type 'talos'.
It appears that the data source is not retrieving the correct metadata, leading to this inconsistency.
```

### Acceptance Criteria

Please fix it as the current version of the data source will stay useless if left this way. 
 
- The `civo_kubernetes_version` data source returns the label attribute in the `'talos-vX.Y.Z'` format for Talos clusters.
- Terraform plans execute successfully without version format errors when using the label from the data source for Talos clusters.

**Comment by Praveen005** [comment]
Hi @brokedba, Thank You for creating the ticket. We are working on this, and a fix will be pushed very shortly.

**Comment by brokedba** [comment]
any update ?

**Comment by Praveen005** [comment]
Hi @brokedba, the error: `Error: invalid Kubernetes version format: '1.27.0' for cluster type 'talos'.
It appears that the data source is not retrieving the correct metadata, leading to this inconsistency.` gets fixed by the last API change that we discussed in https://github.com/civo/terraform-provider-civo/issues/365.


For the incorrect label from the datasource, I have this [PR](https://github.com/civo/terraform-provider-civo/pull/367) in place to correct that.

**Comment by brokedba** [comment]
@Praveen005 that doesn't fix the version displayed in the data source . especially when users try to leverage the version from the data source instead of hardcoding it through a variable.  I think it either should be `talos.x.y.z` or `1.x.y.z` and not a mix. 

```hcl
[
  {
    "default": true,
    "label": "v1.27.0",
    "type": "talos",
    "version": "1.27.0"      <---- wrong   , should be talos-v1.5.0 for example as there is still confusion between label an version
  }
]
```

also, as future enhancement request it'd be nice to have the type field (.i.e `stable`) for a better/granular search .
